name: Build macOS Electron App

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      # If you want to auto-publish to GitHub Releases, pass GH_TOKEN:
      - name: Build the macOS App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG
          path: dist/*.dmg
