name: Build Electron App for Windows & macOS

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac-x64:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # avoid EBADENGINE warnings

      - name: Install dependencies
        run: npm install

      - name: Build x64
        run: npm run build:mac-x64

      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-x64-dmg
          path: dist/*.dmg

      - name: Publish Mac (Intel) build
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-mac-arm64:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build arm64
        run: npm run build:mac-arm64

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm64-dmg
          path: dist/*.dmg
      
      - name: Publish Mac (Silicone) build
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
 

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows app
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/*

      - name: Publish Windows build
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
