name: Build Electron App for Windows & macOS

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac-x64:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build & Publish macOS x64
        run: npm run build:mac-x64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-mac-arm64:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build & Publish macOS arm64
        run: npm run build:mac-arm64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build & Publish Windows app
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
